### ISSUE TITLE
Set.Movies.Title property

### ISSUE THREAD

**Issue by Nessus85100** [phil65/script.skin.info.service#2]
Hi Phil
Is it possible to add another property for the Movie Sets which will give the number of the movies and the titles only without the plot for every movie ?. IMHO it will be very useful if you want to avoid the scrolling every time you are focus on a set.

**Comment by phil65** [comment]
Just put up some PR ;)

**Comment by Nessus85100** [comment]
It looks like the only thing that must be added is the "title_header" in 'Set.Movies.Title' property https://github.com/phil65/script.skin.info.service/blob/master/Utils.py#L272, plus the check if there is only one movie in the set which i don't know how to do it.

Cheers
Nessus

**Comment by Nessus85100** [comment]
Bump ?

**Comment by phil65** [comment]
Will add it when i find the time
Am 07.03.2015 22:41 schrieb "Nessus85100" <notifications@github.com>:

**Comment by Nessus85100** [comment]
OK, thanks

**Comment by phil65** [comment]
https://github.com/phil65/script.skin.info.service/commit/c408ef8677870d0425a6fec4c6260931da14e1fd

**Comment by Nessus85100** [comment]
Thanks for the addition. Moreover can you add a check if there is only one movie in the set, to display the plot and the movie title and not only the title ?.
Showing only one title under the head line "1 Movies" it's not looks so nice.

**Comment by phil65** [comment]
you should be able to do that on skinning level by using Set.Movie.1.Plot in combination with StringCompare(Set.Movies.Count,1)

**Comment by Nessus85100** [comment]
Is it possible to do this in script so to avoid the additional StringCompare check code ?

**Comment by phil65** [comment]
It´s possible, but I dont like that change.

**Comment by Nessus85100** [comment]
May i ask why ?. IMHO without that the "Set.Movies.List" property is a half working function.

**Comment by phil65** [comment]
Because it is a different type of information (imagine a skinner who shows the set movies in a list and already shows the plot for the focussed one. that way the plot would show up two times.)

**Comment by Nessus85100** [comment]
Ok then. Will do it in the skin.

Thanks
